sudo: required
services:
    - docker

before_install:
    - docker build -t gmagheru/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run gmagheru/react-test npm test -- --coverage

after_success:
    - docker build -t gmagheru/multi-client ./client
    - docker build -t gmagheru/multi-nginx ./nginx
    - docker build -t gmagheru/multi-server ./server
    - docker build -t gmagheru/multi-worker ./worker

#login to the docker client
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#push these images to dockerhub
    - docker push gmagheru/multi-client
    - docker push gmagheru/multi-nginx
    - docker push gmagheru/multi-server
    - docker push gmagheru/multi-worker
