version: '3'

services:

    nginx-component:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'

    postgres-component:
        image: 'postgres:latest'

    redis-component:
        image: 'redis:latest'
    
    server-component:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - '/app/node_modules'
            - './server:/app'
        environment:
            - REDIS_HOST=redis-component
            - REDIS_PORT=6379
            - PGHOST=postgres-component
            - PGPORT=5432
            - PGDATABASE=postgres
            - PGUSER=postgres
            - PGPASSWORD=postgres_password

    client-component:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - '/app/node_modules'
            - './client:/app'

    worker-component:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - '/app/node_modules'
            - './worker:/app'
        environment:
            - REDIS_HOST=redis-component
            - REDIS_PORT=6379
